services:
  - type: web
    name: naukri-automation
    env: node
    plan: free
    branch: main
    buildCommand: |
      npm install
      node node_modules/playwright/install.js chromium
    startCommand: node index.js
    envVars:
      - fromGroup: naukri
