services:
  - type: web
    name: naukri-automation
    env: node
    plan: free
    branch: main
    buildCommand: |
      # Ensure browsers are installed locally in node_modules
      export PLAYWRIGHT_BROWSERS_PATH=0
      npm install
      npx playwright install --with-deps
    startCommand: node index.js
    envVars:
      - fromGroup: naukri
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
