services:
  - type: web
    name: naukri-automation
    env: node
    plan: free
    branch: main
    buildCommand: |
      npm install
      npx playwright install chromium
    startCommand: "node index.js"
    envVars:
      - fromGroup: naukri
