services:
  - type: web
    name: naukri-automation
    env: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - fromGroup: naukri
      - key: NAUKRI_EMAIL
        value: "true"
      - key: NAUKRI_PASSWORD
        value: "true"
